### ISSUE TITLE
Cannot run on gpu

### ISSUE THREAD

**Issue by Aonnghus** [neuronflow/BraTS-Toolkit-Source#1]
Hi,
When I try to run the toolkit on GPU, I end up with the following error: 
`docker: Error response from daemon: OCI runtime create failed: container_linux.go:367: starting container process caused: process_linux.go:495: container init caused: Running hook #0:: error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: initialization error: driver error: failed to process request: unknown.`

It seems to be due to a wrongly installed nvidia driver in the docker image projectelephant/server. I tried to run the docker image directly from command line and it gave me the same error

**Comment by neuronflow** [comment]
Thanks for your interest in btk. What happens if you run the nvidia docker hello world on your system?

which gpu, gpu driver and cuda version do you have?
